### ISSUE TITLE
Improve posts page style

### ISSUE THREAD

**Issue by brown121407** [BoogeyBots/boogeybots-blog#2]
We need some design fixing on the posts page. Now it looks like this:
![capture](https://user-images.githubusercontent.com/24657667/46524940-f53d0f00-c892-11e8-8f57-0290a836e609.PNG)
We'd like it to look something like this:
![site-design-desktop](https://user-images.githubusercontent.com/24657667/46526164-23701e00-c896-11e8-95e4-11e1028d15aa.png)

Refering to fonts, we prefer consolas, that's the one used in the photo, or Ubuntu, or something like that. If you think something looks better, try it, we might like your ideas more than we do ours.

Check out [CONTRIBUTING.md](https://github.com/BoogeyBots/boogeybots-blog/blob/master/CONTRIBUTING.md) for some guidelines on contributions.

**Comment by louillustrator** [comment]
I will try and take a look
