### ISSUE TITLE
Add stuff to the Home page

### ISSUE THREAD

**Issue by brown121407** [BoogeyBots/boogeybots-blog#3]
Currently the Home page is empty. We would like it to look like this:
![Home Page Design](https://github.com/BoogeyBots/Website-Design/blob/master/site-home-page.png?raw=true "Home page design")
, where the big red thing would later be a photo of the team.

Check out [CONTRIBUTING.md](https://github.com/BoogeyBots/boogeybots-blog/blob/master/CONTRIBUTING.md) for some guidelines on contributions.

**Comment by thomas-vl** [comment]
I build this, what kind of technologies do you want to use?
Pure HTML / CSS / JS?
Or do you want to use a CMS like https://ghost.org/?

**Comment by brown121407** [comment]
@thomas-vl We use [pug](https://github.com/pugjs/pug) as the templating engine and for styles we use [scss](https://sass-lang.com/). The site is deployed using [Now](https://zeit.co/now). The file for the home page is [/views/index.pug](https://github.com/BoogeyBots/boogeybots-blog/blob/master/views/index.pug). It's corresponding stylesheet should be created in /public/stylesheets/ . If you need more guidance we'll be more than happy to help.

**Comment by thomas-vl** [comment]
@brown121407 Ok, i will work on this!

**Comment by brown121407** [comment]
Closed as the work for the website moved to https://github.com/BoogeyBots/boogeybots-website
